---
- name: Update systems
  hosts: all
  tasks:
    - name: yum update
      yum:
        name: '*'
        state: latest
        update_cache: yes
      when: ansible_os_family == 'RedHat'

    - block:
        - name: apt update
          apt:
            name: '*'
            state: latest
            update_cache: yes

        - name: apt autoremove
          apt:
            autoremove: yes
      when: ansible_os_family == 'Debian'

